### ISSUE TITLE
Security issue on dependency

### ISSUE THREAD

**Issue by PeterDaveHello** [rvagg/pangyp#8]
> semver Regular Expression Denial of Service

>  Vulnerable: <4.3.2
>  Patched: >=4.3.2
>  Fri Apr 3 2015 19:00:00 GMT-0700 (PDT)
>  CVE-PENDING
>  Credit: Adam Baldwin

https://nodesecurity.io/advisories/semver_redos

**Comment by jacopotarantino** [comment]
+1. I'm using grunt-nsp-shrinkwrap and this dependency is breaking my build. Any chance this could get updated soon?

**Comment by rvagg** [comment]
done, does that help?

**Comment by jacopotarantino** [comment]
@rvagg That was ridiculously fast. You're the best!
